version: "3"

services:

  rng:
    image: secobau/dockercoins:rng-1.0
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

  hasher:
    image: secobau/dockercoins:hasher-1.3
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

  webui:
    image: secobau/dockercoins:webui-1.1
    ports:
      - "8888:80"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

  redis:
    image: redis
    deploy:
      placement:
        constraints:
          - node.role == worker

  worker:
    image: secobau/dockercoins:worker-1.0
    deploy:
      replicas: 33 #Change to 51+ to improve performance
      placement:
        constraints:
          - node.role == worker
