#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      service: php
  template:
    metadata:
      labels:
        service: php
    spec:
      containers:
      -
        image: secobau/php:rc-apache-1.1@sha256:c82dba0a5651b50ec3a8c95b675bde71c58c94511853e380e0a5e40b95f36832
        name: php
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  ports:
  -
    nodePort: 30003
    port: 80
  selector:
    service: php
  type: NodePort
---
#########################################################################
